-- MySQL Script generated by MySQL Workbench
-- Wed Feb  5 14:49:48 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tables` (
  `tableID` INT NOT NULL AUTO_INCREMENT,
  `seatsAvail` INT NULL,
  `status` TINYINT NULL,
  PRIMARY KEY (`tableID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tabs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tabs` (
  `tabID` INT NOT NULL AUTO_INCREMENT,
  `total` DECIMAL(2) NULL,
  `tableID` INT NOT NULL,
  INDEX `tableID_idx` (`tableID` ASC) VISIBLE,
  PRIMARY KEY (`tabID`),
  CONSTRAINT `tableID`
    FOREIGN KEY (`tableID`)
    REFERENCES `mydb`.`tables` (`tableID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`servers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`servers` (
  `employeeID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`employeeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customers` (
  `customerID` INT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `customerEmail` VARCHAR(100) NOT NULL,
  `customerPhone` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`customerID`),
  UNIQUE INDEX `customerPhone_UNIQUE` (`customerPhone` ASC) VISIBLE,
  UNIQUE INDEX `customerEmail_UNIQUE` (`customerEmail` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reservations` (
  `reservationID` INT NOT NULL AUTO_INCREMENT,
  `reservationDateTime` DATETIME NOT NULL,
  `customerID` INT NOT NULL,
  `employeeID` INT NULL,
  `tableID` INT NULL,
  PRIMARY KEY (`reservationID`),
  INDEX `customerID_idx` (`customerID` ASC) VISIBLE,
  INDEX `employeeID_idx` (`employeeID` ASC) VISIBLE,
  INDEX `tableID_idx` (`tableID` ASC) VISIBLE,
  CONSTRAINT `customerID`
    FOREIGN KEY (`customerID`)
    REFERENCES `mydb`.`customers` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `employeeID`
    FOREIGN KEY (`employeeID`)
    REFERENCES `mydb`.`servers` (`employeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tableID`
    FOREIGN KEY (`tableID`)
    REFERENCES `mydb`.`tables` (`tableID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`serversTables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`serversTables` (
  `tableID` INT NOT NULL,
  `serverID` INT NOT NULL,
  INDEX `serverID_idx` (`serverID` ASC) VISIBLE,
  PRIMARY KEY (`tableID`, `serverID`),
  CONSTRAINT `tableID`
    FOREIGN KEY (`tableID`)
    REFERENCES `mydb`.`tables` (`tableID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `serverID`
    FOREIGN KEY (`serverID`)
    REFERENCES `mydb`.`servers` (`employeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
