-- MySQL Script generated by MySQL Workbench
-- Wed Feb  5 15:47:07 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cs340_vincenty
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cs340_vincenty
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cs340_vincenty` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `cs340_vincenty` ;

-- -----------------------------------------------------
-- Table `cs340_vincenty`.`tables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs340_vincenty`.`tables` (
  `tableID` INT NOT NULL AUTO_INCREMENT,
  `seatsAvail` INT NULL,
  `status` TINYINT NULL,
  PRIMARY KEY (`tableID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs340_vincenty`.`tabs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs340_vincenty`.`tabs` (
  `tabID` INT NOT NULL AUTO_INCREMENT,
  `total` DECIMAL(10,2) NULL,
  `tableID` INT NOT NULL,
  INDEX `tableID_idx` (`tableID` ASC) VISIBLE,
  PRIMARY KEY (`tabID`),
  CONSTRAINT `fkTabsTableID`
    FOREIGN KEY (`tableID`)
    REFERENCES `cs340_vincenty`.`tables` (`tableID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs340_vincenty`.`servers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs340_vincenty`.`servers` (
  `employeeID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`employeeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs340_vincenty`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs340_vincenty`.`customers` (
  `customerID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `customerEmail` VARCHAR(100) NOT NULL,
  `customerPhone` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`customerID`),
  UNIQUE INDEX `customerPhone_UNIQUE` (`customerPhone` ASC) VISIBLE,
  UNIQUE INDEX `customerEmail_UNIQUE` (`customerEmail` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs340_vincenty`.`reservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs340_vincenty`.`reservations` (
  `reservationID` INT NOT NULL AUTO_INCREMENT,
  `reservationDateTime` DATETIME NOT NULL,
  `customerID` INT NOT NULL,
  `employeeID` INT NULL,
  `tableID` INT NULL,
  `status` ENUM('pending', 'cancelled', 'active') NULL,
  PRIMARY KEY (`reservationID`),
  INDEX `customerID_idx` (`customerID` ASC) VISIBLE,
  INDEX `employeeID_idx` (`employeeID` ASC) VISIBLE,
  INDEX `tableID_idx` (`tableID` ASC) VISIBLE,
  CONSTRAINT `fkReservationCustomerID`
    FOREIGN KEY (`customerID`)
    REFERENCES `cs340_vincenty`.`customers` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkReservationEmployeeID`
    FOREIGN KEY (`employeeID`)
    REFERENCES `cs340_vincenty`.`servers` (`employeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkReservationTableID`
    FOREIGN KEY (`tableID`)
    REFERENCES `cs340_vincenty`.`tables` (`tableID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs340_vincenty`.`serversTables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs340_vincenty`.`serversTables` (
  `tableID` INT NOT NULL,
  `serverID` INT NOT NULL,
  `dateTime` DATETIME GENERATED ALWAYS AS () VIRTUAL,
  INDEX `serverID_idx` (`serverID` ASC) VISIBLE,
  PRIMARY KEY (`serverID`, `tableID`),
  CONSTRAINT `fkInterSecTableID`
    FOREIGN KEY (`tableID`)
    REFERENCES `cs340_vincenty`.`tables` (`tableID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkInterSecServerID`
    FOREIGN KEY (`serverID`)
    REFERENCES `cs340_vincenty`.`servers` (`employeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
